// Code generated by counterfeiter. DO NOT EDIT.
package storagev1fake

import (
	"context"
	"sync"

	"cloud.google.com/go/storage"
	storagev1 "github.com/connect-sdk/storage-api/proto/connect/storage/v1"
)

type FakeStorageObjectCopier struct {
	ObjectAttrsStub        func() *storage.ObjectAttrs
	objectAttrsMutex       sync.RWMutex
	objectAttrsArgsForCall []struct {
	}
	objectAttrsReturns struct {
		result1 *storage.ObjectAttrs
	}
	objectAttrsReturnsOnCall map[int]struct {
		result1 *storage.ObjectAttrs
	}
	RunStub        func(context.Context) (*storage.ObjectAttrs, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 *storage.ObjectAttrs
		result2 error
	}
	runReturnsOnCall map[int]struct {
		result1 *storage.ObjectAttrs
		result2 error
	}
	SetDestinationKMSKeyNameStub        func(string)
	setDestinationKMSKeyNameMutex       sync.RWMutex
	setDestinationKMSKeyNameArgsForCall []struct {
		arg1 string
	}
	SetProgressFuncStub        func(func(uint64, uint64))
	setProgressFuncMutex       sync.RWMutex
	setProgressFuncArgsForCall []struct {
		arg1 func(uint64, uint64)
	}
	SetRewriteTokenStub        func(string)
	setRewriteTokenMutex       sync.RWMutex
	setRewriteTokenArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStorageObjectCopier) ObjectAttrs() *storage.ObjectAttrs {
	fake.objectAttrsMutex.Lock()
	ret, specificReturn := fake.objectAttrsReturnsOnCall[len(fake.objectAttrsArgsForCall)]
	fake.objectAttrsArgsForCall = append(fake.objectAttrsArgsForCall, struct {
	}{})
	stub := fake.ObjectAttrsStub
	fakeReturns := fake.objectAttrsReturns
	fake.recordInvocation("ObjectAttrs", []interface{}{})
	fake.objectAttrsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorageObjectCopier) ObjectAttrsCallCount() int {
	fake.objectAttrsMutex.RLock()
	defer fake.objectAttrsMutex.RUnlock()
	return len(fake.objectAttrsArgsForCall)
}

func (fake *FakeStorageObjectCopier) ObjectAttrsCalls(stub func() *storage.ObjectAttrs) {
	fake.objectAttrsMutex.Lock()
	defer fake.objectAttrsMutex.Unlock()
	fake.ObjectAttrsStub = stub
}

func (fake *FakeStorageObjectCopier) ObjectAttrsReturns(result1 *storage.ObjectAttrs) {
	fake.objectAttrsMutex.Lock()
	defer fake.objectAttrsMutex.Unlock()
	fake.ObjectAttrsStub = nil
	fake.objectAttrsReturns = struct {
		result1 *storage.ObjectAttrs
	}{result1}
}

func (fake *FakeStorageObjectCopier) ObjectAttrsReturnsOnCall(i int, result1 *storage.ObjectAttrs) {
	fake.objectAttrsMutex.Lock()
	defer fake.objectAttrsMutex.Unlock()
	fake.ObjectAttrsStub = nil
	if fake.objectAttrsReturnsOnCall == nil {
		fake.objectAttrsReturnsOnCall = make(map[int]struct {
			result1 *storage.ObjectAttrs
		})
	}
	fake.objectAttrsReturnsOnCall[i] = struct {
		result1 *storage.ObjectAttrs
	}{result1}
}

func (fake *FakeStorageObjectCopier) Run(arg1 context.Context) (*storage.ObjectAttrs, error) {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorageObjectCopier) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeStorageObjectCopier) RunCalls(stub func(context.Context) (*storage.ObjectAttrs, error)) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeStorageObjectCopier) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorageObjectCopier) RunReturns(result1 *storage.ObjectAttrs, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 *storage.ObjectAttrs
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageObjectCopier) RunReturnsOnCall(i int, result1 *storage.ObjectAttrs, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 *storage.ObjectAttrs
			result2 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 *storage.ObjectAttrs
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageObjectCopier) SetDestinationKMSKeyName(arg1 string) {
	fake.setDestinationKMSKeyNameMutex.Lock()
	fake.setDestinationKMSKeyNameArgsForCall = append(fake.setDestinationKMSKeyNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetDestinationKMSKeyNameStub
	fake.recordInvocation("SetDestinationKMSKeyName", []interface{}{arg1})
	fake.setDestinationKMSKeyNameMutex.Unlock()
	if stub != nil {
		fake.SetDestinationKMSKeyNameStub(arg1)
	}
}

func (fake *FakeStorageObjectCopier) SetDestinationKMSKeyNameCallCount() int {
	fake.setDestinationKMSKeyNameMutex.RLock()
	defer fake.setDestinationKMSKeyNameMutex.RUnlock()
	return len(fake.setDestinationKMSKeyNameArgsForCall)
}

func (fake *FakeStorageObjectCopier) SetDestinationKMSKeyNameCalls(stub func(string)) {
	fake.setDestinationKMSKeyNameMutex.Lock()
	defer fake.setDestinationKMSKeyNameMutex.Unlock()
	fake.SetDestinationKMSKeyNameStub = stub
}

func (fake *FakeStorageObjectCopier) SetDestinationKMSKeyNameArgsForCall(i int) string {
	fake.setDestinationKMSKeyNameMutex.RLock()
	defer fake.setDestinationKMSKeyNameMutex.RUnlock()
	argsForCall := fake.setDestinationKMSKeyNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorageObjectCopier) SetProgressFunc(arg1 func(uint64, uint64)) {
	fake.setProgressFuncMutex.Lock()
	fake.setProgressFuncArgsForCall = append(fake.setProgressFuncArgsForCall, struct {
		arg1 func(uint64, uint64)
	}{arg1})
	stub := fake.SetProgressFuncStub
	fake.recordInvocation("SetProgressFunc", []interface{}{arg1})
	fake.setProgressFuncMutex.Unlock()
	if stub != nil {
		fake.SetProgressFuncStub(arg1)
	}
}

func (fake *FakeStorageObjectCopier) SetProgressFuncCallCount() int {
	fake.setProgressFuncMutex.RLock()
	defer fake.setProgressFuncMutex.RUnlock()
	return len(fake.setProgressFuncArgsForCall)
}

func (fake *FakeStorageObjectCopier) SetProgressFuncCalls(stub func(func(uint64, uint64))) {
	fake.setProgressFuncMutex.Lock()
	defer fake.setProgressFuncMutex.Unlock()
	fake.SetProgressFuncStub = stub
}

func (fake *FakeStorageObjectCopier) SetProgressFuncArgsForCall(i int) func(uint64, uint64) {
	fake.setProgressFuncMutex.RLock()
	defer fake.setProgressFuncMutex.RUnlock()
	argsForCall := fake.setProgressFuncArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorageObjectCopier) SetRewriteToken(arg1 string) {
	fake.setRewriteTokenMutex.Lock()
	fake.setRewriteTokenArgsForCall = append(fake.setRewriteTokenArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetRewriteTokenStub
	fake.recordInvocation("SetRewriteToken", []interface{}{arg1})
	fake.setRewriteTokenMutex.Unlock()
	if stub != nil {
		fake.SetRewriteTokenStub(arg1)
	}
}

func (fake *FakeStorageObjectCopier) SetRewriteTokenCallCount() int {
	fake.setRewriteTokenMutex.RLock()
	defer fake.setRewriteTokenMutex.RUnlock()
	return len(fake.setRewriteTokenArgsForCall)
}

func (fake *FakeStorageObjectCopier) SetRewriteTokenCalls(stub func(string)) {
	fake.setRewriteTokenMutex.Lock()
	defer fake.setRewriteTokenMutex.Unlock()
	fake.SetRewriteTokenStub = stub
}

func (fake *FakeStorageObjectCopier) SetRewriteTokenArgsForCall(i int) string {
	fake.setRewriteTokenMutex.RLock()
	defer fake.setRewriteTokenMutex.RUnlock()
	argsForCall := fake.setRewriteTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorageObjectCopier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.objectAttrsMutex.RLock()
	defer fake.objectAttrsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	fake.setDestinationKMSKeyNameMutex.RLock()
	defer fake.setDestinationKMSKeyNameMutex.RUnlock()
	fake.setProgressFuncMutex.RLock()
	defer fake.setProgressFuncMutex.RUnlock()
	fake.setRewriteTokenMutex.RLock()
	defer fake.setRewriteTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStorageObjectCopier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storagev1.StorageObjectCopier = new(FakeStorageObjectCopier)
