// Code generated by counterfeiter. DO NOT EDIT.
package storagev1fake

import (
	"sync"

	"cloud.google.com/go/storage"
	storagev1 "github.com/connect-sdk/storage-api/proto/connect/storage/v1"
)

type FakeStorageObjectIterator struct {
	NextStub        func() (*storage.ObjectAttrs, error)
	nextMutex       sync.RWMutex
	nextArgsForCall []struct {
	}
	nextReturns struct {
		result1 *storage.ObjectAttrs
		result2 error
	}
	nextReturnsOnCall map[int]struct {
		result1 *storage.ObjectAttrs
		result2 error
	}
	PageInfoStub        func() storagev1.StoragePageInfo
	pageInfoMutex       sync.RWMutex
	pageInfoArgsForCall []struct {
	}
	pageInfoReturns struct {
		result1 storagev1.StoragePageInfo
	}
	pageInfoReturnsOnCall map[int]struct {
		result1 storagev1.StoragePageInfo
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStorageObjectIterator) Next() (*storage.ObjectAttrs, error) {
	fake.nextMutex.Lock()
	ret, specificReturn := fake.nextReturnsOnCall[len(fake.nextArgsForCall)]
	fake.nextArgsForCall = append(fake.nextArgsForCall, struct {
	}{})
	stub := fake.NextStub
	fakeReturns := fake.nextReturns
	fake.recordInvocation("Next", []interface{}{})
	fake.nextMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorageObjectIterator) NextCallCount() int {
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	return len(fake.nextArgsForCall)
}

func (fake *FakeStorageObjectIterator) NextCalls(stub func() (*storage.ObjectAttrs, error)) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = stub
}

func (fake *FakeStorageObjectIterator) NextReturns(result1 *storage.ObjectAttrs, result2 error) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = nil
	fake.nextReturns = struct {
		result1 *storage.ObjectAttrs
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageObjectIterator) NextReturnsOnCall(i int, result1 *storage.ObjectAttrs, result2 error) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = nil
	if fake.nextReturnsOnCall == nil {
		fake.nextReturnsOnCall = make(map[int]struct {
			result1 *storage.ObjectAttrs
			result2 error
		})
	}
	fake.nextReturnsOnCall[i] = struct {
		result1 *storage.ObjectAttrs
		result2 error
	}{result1, result2}
}

func (fake *FakeStorageObjectIterator) PageInfo() storagev1.StoragePageInfo {
	fake.pageInfoMutex.Lock()
	ret, specificReturn := fake.pageInfoReturnsOnCall[len(fake.pageInfoArgsForCall)]
	fake.pageInfoArgsForCall = append(fake.pageInfoArgsForCall, struct {
	}{})
	stub := fake.PageInfoStub
	fakeReturns := fake.pageInfoReturns
	fake.recordInvocation("PageInfo", []interface{}{})
	fake.pageInfoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorageObjectIterator) PageInfoCallCount() int {
	fake.pageInfoMutex.RLock()
	defer fake.pageInfoMutex.RUnlock()
	return len(fake.pageInfoArgsForCall)
}

func (fake *FakeStorageObjectIterator) PageInfoCalls(stub func() storagev1.StoragePageInfo) {
	fake.pageInfoMutex.Lock()
	defer fake.pageInfoMutex.Unlock()
	fake.PageInfoStub = stub
}

func (fake *FakeStorageObjectIterator) PageInfoReturns(result1 storagev1.StoragePageInfo) {
	fake.pageInfoMutex.Lock()
	defer fake.pageInfoMutex.Unlock()
	fake.PageInfoStub = nil
	fake.pageInfoReturns = struct {
		result1 storagev1.StoragePageInfo
	}{result1}
}

func (fake *FakeStorageObjectIterator) PageInfoReturnsOnCall(i int, result1 storagev1.StoragePageInfo) {
	fake.pageInfoMutex.Lock()
	defer fake.pageInfoMutex.Unlock()
	fake.PageInfoStub = nil
	if fake.pageInfoReturnsOnCall == nil {
		fake.pageInfoReturnsOnCall = make(map[int]struct {
			result1 storagev1.StoragePageInfo
		})
	}
	fake.pageInfoReturnsOnCall[i] = struct {
		result1 storagev1.StoragePageInfo
	}{result1}
}

func (fake *FakeStorageObjectIterator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	fake.pageInfoMutex.RLock()
	defer fake.pageInfoMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStorageObjectIterator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storagev1.StorageObjectIterator = new(FakeStorageObjectIterator)
