// Code generated by counterfeiter. DO NOT EDIT.
package storagev1fake

import (
	"context"
	"sync"

	storagev1 "github.com/connect-sdk/storage-api/proto/connect/storage/v1"
)

type FakeStorageServiceClient struct {
	BucketStub        func(string) storagev1.StorageBucketHandle
	bucketMutex       sync.RWMutex
	bucketArgsForCall []struct {
		arg1 string
	}
	bucketReturns struct {
		result1 storagev1.StorageBucketHandle
	}
	bucketReturnsOnCall map[int]struct {
		result1 storagev1.StorageBucketHandle
	}
	BucketsStub        func(context.Context, string) storagev1.StorageBucketIterator
	bucketsMutex       sync.RWMutex
	bucketsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	bucketsReturns struct {
		result1 storagev1.StorageBucketIterator
	}
	bucketsReturnsOnCall map[int]struct {
		result1 storagev1.StorageBucketIterator
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStorageServiceClient) Bucket(arg1 string) storagev1.StorageBucketHandle {
	fake.bucketMutex.Lock()
	ret, specificReturn := fake.bucketReturnsOnCall[len(fake.bucketArgsForCall)]
	fake.bucketArgsForCall = append(fake.bucketArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.BucketStub
	fakeReturns := fake.bucketReturns
	fake.recordInvocation("Bucket", []interface{}{arg1})
	fake.bucketMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorageServiceClient) BucketCallCount() int {
	fake.bucketMutex.RLock()
	defer fake.bucketMutex.RUnlock()
	return len(fake.bucketArgsForCall)
}

func (fake *FakeStorageServiceClient) BucketCalls(stub func(string) storagev1.StorageBucketHandle) {
	fake.bucketMutex.Lock()
	defer fake.bucketMutex.Unlock()
	fake.BucketStub = stub
}

func (fake *FakeStorageServiceClient) BucketArgsForCall(i int) string {
	fake.bucketMutex.RLock()
	defer fake.bucketMutex.RUnlock()
	argsForCall := fake.bucketArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorageServiceClient) BucketReturns(result1 storagev1.StorageBucketHandle) {
	fake.bucketMutex.Lock()
	defer fake.bucketMutex.Unlock()
	fake.BucketStub = nil
	fake.bucketReturns = struct {
		result1 storagev1.StorageBucketHandle
	}{result1}
}

func (fake *FakeStorageServiceClient) BucketReturnsOnCall(i int, result1 storagev1.StorageBucketHandle) {
	fake.bucketMutex.Lock()
	defer fake.bucketMutex.Unlock()
	fake.BucketStub = nil
	if fake.bucketReturnsOnCall == nil {
		fake.bucketReturnsOnCall = make(map[int]struct {
			result1 storagev1.StorageBucketHandle
		})
	}
	fake.bucketReturnsOnCall[i] = struct {
		result1 storagev1.StorageBucketHandle
	}{result1}
}

func (fake *FakeStorageServiceClient) Buckets(arg1 context.Context, arg2 string) storagev1.StorageBucketIterator {
	fake.bucketsMutex.Lock()
	ret, specificReturn := fake.bucketsReturnsOnCall[len(fake.bucketsArgsForCall)]
	fake.bucketsArgsForCall = append(fake.bucketsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.BucketsStub
	fakeReturns := fake.bucketsReturns
	fake.recordInvocation("Buckets", []interface{}{arg1, arg2})
	fake.bucketsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorageServiceClient) BucketsCallCount() int {
	fake.bucketsMutex.RLock()
	defer fake.bucketsMutex.RUnlock()
	return len(fake.bucketsArgsForCall)
}

func (fake *FakeStorageServiceClient) BucketsCalls(stub func(context.Context, string) storagev1.StorageBucketIterator) {
	fake.bucketsMutex.Lock()
	defer fake.bucketsMutex.Unlock()
	fake.BucketsStub = stub
}

func (fake *FakeStorageServiceClient) BucketsArgsForCall(i int) (context.Context, string) {
	fake.bucketsMutex.RLock()
	defer fake.bucketsMutex.RUnlock()
	argsForCall := fake.bucketsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStorageServiceClient) BucketsReturns(result1 storagev1.StorageBucketIterator) {
	fake.bucketsMutex.Lock()
	defer fake.bucketsMutex.Unlock()
	fake.BucketsStub = nil
	fake.bucketsReturns = struct {
		result1 storagev1.StorageBucketIterator
	}{result1}
}

func (fake *FakeStorageServiceClient) BucketsReturnsOnCall(i int, result1 storagev1.StorageBucketIterator) {
	fake.bucketsMutex.Lock()
	defer fake.bucketsMutex.Unlock()
	fake.BucketsStub = nil
	if fake.bucketsReturnsOnCall == nil {
		fake.bucketsReturnsOnCall = make(map[int]struct {
			result1 storagev1.StorageBucketIterator
		})
	}
	fake.bucketsReturnsOnCall[i] = struct {
		result1 storagev1.StorageBucketIterator
	}{result1}
}

func (fake *FakeStorageServiceClient) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorageServiceClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeStorageServiceClient) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeStorageServiceClient) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageServiceClient) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorageServiceClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.bucketMutex.RLock()
	defer fake.bucketMutex.RUnlock()
	fake.bucketsMutex.RLock()
	defer fake.bucketsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStorageServiceClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storagev1.StorageServiceClient = new(FakeStorageServiceClient)
